[package]
name = "dbkv"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.2"
crc = "1.7"
serde = "1"
serde_derive = "1"

[lib]
name = "dbkv"
path = "src/lib.rs"
 
[[bin]]
name = "kv_mem"
path = "src/kv_mem.rs"
